version: '3.8'
services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:7.2.4-alpine
    container_name: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local

networks:
  app-net:
    driver: bridge
